@extends('layouts.app')

@section('content')


<h2 class="mt-5 pb-2 display-5 border-bottom">賞レース年間スケジュール</h2>

<table class="table table-striped">
	<thead>
		<tr>
			<th >
				開催月
			</th>
			<th>
				大会名
			</th>
			<th>
				受賞対象
			</th>
			<th>
				賞金
			</th>
			<th>
				初回
			</th>
			<th>
				決勝ネタ時間
			</th>
			<th>
				URL
			</th>
		</tr>
	</thead>
	
	<tbody>
		<tr>
			<th>
				1月
			</th>
			<td>
				上方漫才協会大賞
			</td>
			<td>
				上方漫才協会に所属する芸歴約10年以内の漫才師
			</td>
			<td>
				-
			</td>
			<td>
				2016年
			</td>
			<td>
				-
			</td>
			<td>
				<a href="https://www.yoshimoto.co.jp/kamigatamanzaikyokai/award/" target="_blank" rel="noopener noreferrer"><img src="https://www.geireki.net/icon/web.png" alt="漫才賞レース年間スケジュール"></a>
			</td>
		</tr>
		<tr>
			<th>
				1月
			</th>
			<td>
				新春!oh笑い O-1グランプリ
			</td>
			<td>
				沖縄県内で活動するお笑い好きな者。ジャンルや人数、プロ・アマは不問となっている。
			</td>
			<td>
				30万円
			</td>
			<td>
				2007年
			</td>
			<td>
				4分
			</td>
			<td>
				<a href="https://o1gp.otv.co.jp/" target="_blank" rel="noopener noreferrer"><img src="https://www.geireki.net/icon/web.png" alt="漫才賞レース年間スケジュール"></a>
			</td>
		</tr>
		<tr>
			<th>
				2月
			</th>
			<td>
				NHK上方漫才コンテスト
			</td>
			<td>
				結成10年未満のプロの芸人
			</td>
			<td>
				50万円
			</td>
			<td>
				1971年
			</td>
			<td>
				8分
			</td>
			<td>
				<a href="https://www.nhk.jp/p/ts/D5885G8PKJ/" target="_blank" rel="noopener noreferrer"><img src="https://www.geireki.net/icon/web.png" alt="漫才賞レース年間スケジュール"></a>
			</td>
		</tr>
		<tr>
			<th>
				3月
			</th>
			<td>
				R1グランプリ
			</td>
			<td>
				芸歴10年以内のピン芸人
			</td>
			<td>
				500万円
			</td>
			<td>
				2002年
			</td>
			<td>
				4分
			</td>
			<td>
				<a href="https://www.r-1gp.com/" target="_blank" rel="noopener noreferrer"><img src="https://www.geireki.net/icon/web.png" alt="漫才賞レース年間スケジュール"></a>
			</td>
		</tr>
		<tr>
			<th>
				3月
			</th>
			<td>
				花形演芸会・花形演芸大賞
			</td>
			<td>
				入門から20年以内の若手
			</td>
			<td>
				-
			</td>
			<td>
				1997年
			</td>
			<td>
				-
			</td>
			<td>
				<a href="https://www.ntj.jac.go.jp/gekijo/engei/index.html" target="_blank" rel="noopener noreferrer"><img src="https://www.geireki.net/icon/web.png" alt="漫才賞レース年間スケジュール"></a>
			</td>
		</tr>
		<tr>
			<th>
				3月
			</th>
			<td>
				ytv漫才新人賞
			</td>
			<td>
				大阪を拠点に活動する芸歴10年までの漫才師
			</td>
			<td>
				100万円
			</td>
			<td>
				2012年
			</td>
			<td>
				5分
			</td>
			<td>
				<a href="https://www.ytv.co.jp/manzai/index.html" target="_blank" rel="noopener noreferrer"><img src="https://www.geireki.net/icon/web.png" alt="漫才賞レース年間スケジュール"></a>
			</td>
		</tr>
		<tr>
			<th>
				4月
			</th>
			<td>
				上方漫才大賞
			</td>
			<td>
					上方漫才界のすべての漫才師の中でその年最も活躍した漫才師
			</td>
			<td>
				200万円
			</td>
			<td>
				1966年
			</td>
			<td>
				-
			</td>
			<td>
				<a href="https://www.obc1314.co.jp/kamigata/" target="_blank" rel="noopener noreferrer"><img src="https://www.geireki.net/icon/web.png" alt="漫才賞レース年間スケジュール"></a>
			</td>
		</tr>
		<tr>
			<th>
				4月
			</th>
			<td>
				G-1グランプリ
			</td>
			<td>
				芸歴15年以上のお笑い芸人
			</td>
			<td>
				300万円
			</td>
			<td>
				2022年
			</td>
			<td>
				4分
			</td>
			<td>
				<a href="https://jikata-no1.com/" target="_blank" rel="noopener noreferrer"><img src="https://www.geireki.net/icon/web.png" alt="漫才賞レース年間スケジュール"></a>
			</td>
		</tr>
		<tr>
			<th>
				5月
			</th>
			<td>
				ツギクル芸人グランプリ
			</td>
			<td>
				地上波のプライムタイムのテレビ番組レギュラーを持たないお笑い芸人
			</td>
			<td>
				100万円
			</td>
			<td>
				2019年
			</td>
			<td>
				4分
			</td>
			<td>
				<a href="https://www.fujitv.co.jp/tsugikuru/" target="_blank" rel="noopener noreferrer"><img src="https://www.geireki.net/icon/web.png" alt="漫才賞レース年間スケジュール"></a>
				
			</td>
		</tr>
		<tr>
			<th>
				7月
			</th>
			<td>
				今宮子供えびすマンザイ新人コンクール
			</td>
			<td>
				プロを目指していて、過去に受賞経験のないコンビもしくはグループ
			</td>
			<td>
				20万
			</td>
			<td>
				1980年
			</td>
			<td>
				-
			</td>
			<td>
					<a href="https://www.imamiya-ebisu.jp/kodomo" target="_blank" rel="noopener noreferrer"><img src="https://www.geireki.net/icon/web.png" alt="漫才賞レース年間スケジュール"></a>
				
			</td>
		</tr>
		<tr>
			<th>
				7月
			</th>
			<td>
				ABCお笑いグランプリ
			</td>
			<td>
					デビュー10年以内のお笑い芸人
			</td>
			<td>
				100万円
			</td>
			<td>
				2012年
			</td>
			<td>
				4分
			</td>
			<td>
					<a href="https://asahi.co.jp/owarai/" target="_blank" rel="noopener noreferrer"><img src="https://www.geireki.net/icon/web.png" alt="漫才賞レース年間スケジュール"></a>
				
			</td>
		</tr>
		<tr>
			<th>
				7月
			</th>
			<td>
				漫才新人大賞
			</td>
			<td>
				漫才協会に所属する結成20年以内の漫才コンビに限る
			</td>
			<td>
				10万円
			</td>
			<td>
				2002年
			</td>
			<td>
				10分
			</td>
			<td>
					<a href="http://www.manzaikyokai.org/about/note/shinjin-contest/" target="_blank" rel="noopener noreferrer"><img src="https://www.geireki.net/icon/web.png" alt="漫才賞レース年間スケジュール"></a>
				
			</td>
		</tr>
		<tr>
			<th>
				7月
			</th>
			<td>
				笑ラウドネスGP
			</td>
			<td>
				なし
			</td>
			<td>
				得点×1万円
			</td>
			<td>
				2021年
			</td>
			<td>
				-
			</td>
			<td>
					<a href="https://waraudoness.com/" target="_blank" rel="noopener noreferrer"><img src="https://www.geireki.net/icon/web.png" alt="漫才賞レース年間スケジュール"></a>
				
			</td>
		</tr>
		<tr>
			<th>
				8月
			</th>
			<td>
				お笑いバイアスロン
			</td>
			<td>
				プロ、アマ、所属会社・事務所、芸歴、一切問わず
			</td>
			<td>
				50万円
			</td>
			<td>
				2013年
			</td>
			<td>
				3分
			</td>
			<td>
					<a href="https://www.qab.co.jp/biathlon2013/" target="_blank" rel="noopener noreferrer"><img src="https://www.geireki.net/icon/web.png" alt="漫才賞レース年間スケジュール"></a>
				
			</td>
		</tr>
		<tr>
			<th>
				9月
			</th>
			<td>
				関西演芸しゃべくり話芸大賞
			</td>
			<td>
				漫才・漫談・スタンダップコメディなど
			</td>
			<td>
				30万円
			</td>
			<td>
				2012年
			</td>
			<td>
				7分
			</td>
			<td>
					<a href="http://www.walive.org/index.html" target="_blank" rel="noopener noreferrer"><img src="https://www.geireki.net/icon/web.png" alt="漫才賞レース年間スケジュール"></a>
				
			</td>
		</tr>
		<tr>
			<th>
				9月
			</th>
			<td>
				新人お笑い尼崎大賞
			</td>
			<td>
				新人であり、過去に「新人お笑い尼崎大賞」の大賞を受賞していないこと
			</td>
			<td>
				10万円
			</td>
			<td>
				2001年
			</td>
			<td>
				10分以内
			</td>
			<td>
					<a href="https://www.archaic.or.jp/event/owarai/" target="_blank" rel="noopener noreferrer"><img src="https://www.geireki.net/icon/web.png" alt="漫才賞レース年間スケジュール"></a>
				
			</td>
		</tr>
		<tr>
			<th>
				10月
			</th>
			<td>
				キングオブコント
			</td>
			<td>
				お笑い芸人（2人以上）
			</td>
			<td>
				1000万円
			</td>
			<td>
				2008年
			</td>
			<td>
				5分
			</td>
			<td>
					<a href="https://king-of-conte.com/" target="_blank" rel="noopener noreferrer"><img src="https://www.geireki.net/icon/web.png" alt="漫才賞レース年間スケジュール"></a>
				
			</td>
		</tr>
		<tr>
			<th>
				10月
			</th>
			<td>
				NHK新人演芸大賞
			</td>
			<td>
				結成10年未満のプロの芸人
			</td>
			<td>
				50万円
			</td>
			<td>
				1956年
			</td>
			<td>
				-
			</td>
			<td>
					<a href="https://www.nhk.jp/p/ts/34KQQWPZLV/" target="_blank" rel="noopener noreferrer"><img src="https://www.geireki.net/icon/web.png" alt="漫才賞レース年間スケジュール"></a>
				
			</td>
		</tr>
		<tr>
			<th>
				12月
			</th>
			<td>
				女芸人No.1決定戦 THE W
			</td>
			<td>
				女性のお笑い芸人
			</td>
			<td>
				1000万円
			</td>
			<td>
				2017年
			</td>
			<td>
				4分
			</td>
			<td>
					<a href="https://www.ntv.co.jp/w2021/" target="_blank" rel="noopener noreferrer"><img src="https://www.geireki.net/icon/web.png" alt="漫才賞レース年間スケジュール"></a>
				
			</td>
		</tr>
		<tr>
			<th nowrap>
				12月
			</th>
			<td>
				M1グランプリ
			</td>
			<td>
				結成15年以内の漫才師（2人以上）
			</td>
			<td>
				1000万円
			</td>
			<td>
				2001年
			</td>
			<td>
				4分
			</td>
			<td>
					<a href="https://www.m-1gp.com/" target="_blank" rel="noopener noreferrer"><img src="https://www.geireki.net/icon/web.png" alt="漫才賞レース年間スケジュール"></a>			    
				
			</td>
		</tr>
	</tbody>
</table>

@endsection        